### ISSUE TITLE
Problem uplodaing webGui nodes in FreeCAD

### ISSUE THREAD

**Issue by NogaObs** [HermesFlow/pyHermes#51]
There is a blank web display instead of the webGui nodes
- try to Install branch noga21 again on my computer -> see if problem happens

**Comment by NogaObs** [comment]
Hi @yehudarav ,
Jack and I reinstall the docker on my computer.
The webGui is working.
Jack asked if you could check 2 things:
1. Try to upload some node webGui - for example controlDict -> if it seem to finish loading from status bar, but still blank page, maybe it is a color problem. The suggestion is to try to copy from FreeCAD controlDict webGui web display to random editor to see if the data is exist, but just dont display as it should.
2. check the docker upload output -> if you could copy from terminal all the things that print out from running the docker, till the FreeCAD is loaded,   and send us / upload here?

**Comment by yehudarav** [comment]
Hi,

I have attached the source of the HTML file that I get (just clicked on the
controlDict node, waited until it stopped loading and then
right click -> get source).

Maybe the problem is in our code because I get these errors in the FreeCAD
console:


Node onDocumentRestored
Node onDocumentRestored
Node onDocumentRestored
Node onDocumentRestored
onDocumentRestored
Node onDocumentRestored
Node onDocumentRestored
Node onDocumentRestored
Node onDocumentRestored
Traceback (most recent call last):
  File "/mnt/build/Mod/Hermes_git/HermesNode.py", line 248, in
onDocumentRestored
    workflowObj.Proxy.nLastNodeId = "-1"
<class 'AttributeError'>: 'NoneType' object has no attribute 'nLastNodeId'
Traceback (most recent call last):
  File "/mnt/build/Mod/Hermes_git/HermesNode.py", line 248, in
onDocumentRestored
    workflowObj.Proxy.nLastNodeId = "-1"
<class 'AttributeError'>: 'NoneType' object has no attribute 'nLastNodeId'
Traceback (most recent call last):
  File "/mnt/build/Mod/Hermes_git/HermesNode.py", line 248, in
onDocumentRestored
    workflowObj.Proxy.nLastNodeId = "-1"
<class 'AttributeError'>: 'NoneType' object has no attribute 'nLastNodeId'
Traceback (most recent call last):
  File "/mnt/build/Mod/Hermes_git/HermesNode.py", line 248, in
onDocumentRestored
    workflowObj.Proxy.nLastNodeId = "-1"
<class 'AttributeError'>: 'NoneType' object has no attribute 'nLastNodeId'
Traceback (most recent call last):
  File "/mnt/build/Mod/Hermes_git/HermesNode.py", line 248, in
onDocumentRestored
    workflowObj.Proxy.nLastNodeId = "-1"
<class 'AttributeError'>: 'NoneType' object has no attribute 'nLastNodeId'
Traceback (most recent call last):
  File "/mnt/build/Mod/Hermes_git/HermesNode.py", line 248, in
onDocumentRestored
    workflowObj.Proxy.nLastNodeId = "-1"
<class 'AttributeError'>: 'NoneType' object has no attribute 'nLastNodeId'
Traceback (most recent call last):
  File "/mnt/build/Mod/Hermes_git/HermesNode.py", line 248, in
onDocumentRestored
    workflowObj.Proxy.nLastNodeId = "-1"
<class 'AttributeError'>: 'NoneType' object has no attribute 'nLastNodeId'
Traceback (most recent call last):
  File "/mnt/build/Mod/Hermes_git/HermesNode.py", line 349, in getIcon
    if self.NodeObjType == "WebGuiNode":
<class 'AttributeError'>: '_ViewProviderNode' object has no attribute
'NodeObjType'
Traceback (most recent call last):
  File "/mnt/build/Mod/Hermes_git/HermesNode.py", line 349, in getIcon
    if self.NodeObjType == "WebGuiNode":
<class 'AttributeError'>: '_ViewProviderNode' object has no attribute
'NodeObjType'
Traceback (most recent call last):
  File "/mnt/build/Mod/Hermes_git/HermesNode.py", line 349, in getIcon
    if self.NodeObjType == "WebGuiNode":
<class 'AttributeError'>: '_ViewProviderNode' object has no attribute
'NodeObjType'
Traceback (most recent call last):
  File "/mnt/build/Mod/Hermes_git/HermesNode.py", line 349, in getIcon
    if self.NodeObjType == "WebGuiNode":
<class 'AttributeError'>: '_ViewProviderNode' object has no attribute
'NodeObjType'
Traceback (most recent call last):
  File "/mnt/build/Mod/Hermes_git/HermesNode.py", line 349, in getIcon
    if self.NodeObjType == "WebGuiNode":
<class 'AttributeError'>: '_ViewProviderNode' object has no attribute
'NodeObjType'
Traceback (most recent call last):
  File "/mnt/build/Mod/Hermes_git/HermesNode.py", line 349, in getIcon
    if self.NodeObjType == "WebGuiNode":
<class 'AttributeError'>: '_ViewProviderNode' object has no attribute
'NodeObjType'
Traceback (most recent call last):
  File "/mnt/build/Mod/Hermes_git/HermesNode.py", line 349, in getIcon
    if self.NodeObjType == "WebGuiNode":
<class 'AttributeError'>: '_ViewProviderNode' object has no attribute
'NodeObjType'
Traceback (most recent call last):
  File "/mnt/build/Mod/Hermes_git/HermesNode.py", line 349, in getIcon
    if self.NodeObjType == "WebGuiNode":
<class 'AttributeError'>: '_ViewProviderNode' object has no attribute
'NodeObjType'
Traceback (most recent call last):
  File "/mnt/build/Mod/Hermes_git/HermesNode.py", line 349, in getIcon
    if self.NodeObjType == "WebGuiNode":
<class 'AttributeError'>: '_ViewProviderNode' object has no attribute
'NodeObjType'
Traceback (most recent call last):
  File "/mnt/build/Mod/Hermes_git/HermesNode.py", line 349, in getIcon
    if self.NodeObjType == "WebGuiNode":
<class 'AttributeError'>: '_ViewProviderNode' object has no attribute
'NodeObjType'
Traceback (most recent call last):
  File "/mnt/build/Mod/Hermes_git/HermesNode.py", line 349, in getIcon
    if self.NodeObjType == "WebGuiNode":
<class 'AttributeError'>: '_ViewProviderNode' object has no attribute
'NodeObjType'
Traceback (most recent call last):
  File "/mnt/build/Mod/Hermes_git/HermesNode.py", line 349, in getIcon
    if self.NodeObjType == "WebGuiNode":
<class 'AttributeError'>: '_ViewProviderNode' object has no attribute
'NodeObjType'
Traceback (most recent call last):
  File "/mnt/build/Mod/Hermes_git/HermesNode.py", line 349, in getIcon
    if self.NodeObjType == "WebGuiNode":
<class 'AttributeError'>: '_ViewProviderNode' object has no attribute
'NodeObjType'
Traceback (most recent call last):
  File "/mnt/build/Mod/Hermes_git/HermesNode.py", line 443, in doubleClicked
    vobj.Object.Proxy.doubleClickedNode(vobj.Object)
<class 'AttributeError'>: 'NoneType' object has no attribute
'doubleClickedNode'
Traceback (most recent call last):
  File "/mnt/build/Mod/Hermes_git/HermesNode.py", line 443, in doubleClicked
    vobj.Object.Proxy.doubleClickedNode(vobj.Object)
<class 'AttributeError'>: 'NoneType' object has no attribute
'doubleClickedNode'

**Comment by NogaObs** [comment]
if there are code errors, then FreeCAD definitely won't work.
I did some changes due those errors to branch **noga21**
can u pull the changes and try again?

**Comment by yehudarav** [comment]
טוב, אז אין יותר הדפסות של שגיאה אבל הוא עדיין לא מציג כלום.
הדף שאני מקבל הוא מה ששלחתי לך במייל הקודם.

**Comment by NogaObs** [comment]
רק בשביל לודא - תוכל לשלוח לי את הקובץ
HermesNode.py
לודא ששום דבר לא השתבש דרך המעברים בgit/github

**Comment by yehudarav** [comment]
איפה הוא?

**Comment by NogaObs** [comment]
`hermes/Resources/workbench/HermesNode.py`

**Comment by yehudarav** [comment]
הי, יש לך רעיון לאיך לפתור את הבעיה?

**Comment by NogaObs** [comment]
היי, תוכל לשלוח את הקבצים-
```
hermes/Resources/workbench/HermesNode.py
hermes/Resources/workbench/HermesGui.py
```

כדי שאוכל לעשות השוואה ביחס למה שיש אצלי, לוודא שהם אותו דבר?

**Comment by yehudarav** [comment]
הי נוגה,
מה שלומך? יש איזו התקדמות? אנחנו ננסה להתקין על מחשב אחר

**Comment by NogaObs** [comment]
Hi,
I'm fine, how are u?
I did continue working on reorganise the workbench, add comments and clean, of course in other branch.
Jack tried to install on a different computer and it seen to work there.
Can you do the following steps:
1. Enter FreeCAD
2. upload the JSON file Box_simpleFOAM.json from HermesWorkflow1 node "Import JSON"
3. After it uploaded, click in HemesWorkflow1 Node " Export JSON" and save the file
4. send me the exported file - "HermesWorkflow1.json"?
